# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            BytesClub
tagline:          Coding Club, WBUT In-House
description:      "An open source community for WBUT In-House Students"
url:              https://bytesclub.github.io/
baseurl:          /

author:
  name:           'Bytes CLub'
  url:            https://twitter.com/WBUTcoders

paginate:         5
excerpt_separator: "\n\n"

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/BytesClub

#Global vars
asset-img-path: /img/assets/
asset-path: /assets/
asset-download-path: /downloads/assets/

defaults:
  - scope:
      path: "_assets"
      type: assets
    values:
      layout: asset-view
      banner-img: Banner.jpg
      two-thirds-img: TwoThirds.jpg
      one-third-img: OneThird.jpg
      priority: 10
      show: true
      file-type: .zip

collections:
  assets:
    output: true
    permalink: /:collection/:title/

jekyll_get:
  data: ttt
  json: 'https://api.github.com/repos/BytesClub/Tic_Tac_Toe/contributors'
  cache: true