# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            BytesClub
tagline:          Coding Club, WBUT In-House
description:      "Bytes Club is an open source community for WBUT In-House Students"
url:              https://github.com/BytesClub
baseurl:          /

author:
  name:           'Bytes CLub'
  url:            https://twitter.com/WBUTcoders

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/BytesClub
